CREATE TABLE inventory_item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku         VARCHAR(64)              NOT NULL,
    name        VARCHAR(255)             NOT NULL,
    description VARCHAR(1000),
    quantity    INTEGER                  NOT NULL,
    unit_price  NUMERIC(12, 2)           NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    version     BIGINT                   NOT NULL DEFAULT 0,
    CONSTRAINT uk_inventory_item_sku UNIQUE (sku),
    CONSTRAINT ck_inventory_item_quantity CHECK ( quantity >= 0)
);

CREATE TABLE shipment
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination VARCHAR(255)             NOT NULL,
    status      VARCHAR(20)              NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    version     BIGINT                   NOT NULL DEFAULT 0,
    CONSTRAINT ck_shipment_status CHECK (status IN ('OPEN', 'SHIPPED', 'CANCELLED'))
);
CREATE TABLE shipment_item
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id       BIGINT  NOT NULL REFERENCES shipment (id),
    inventory_item_id BIGINT  NOT NULL REFERENCES inventory_item (id),
    quantity          INTEGER NOT NULL,
    CONSTRAINT uk_shipment_item UNIQUE (shipment_id, inventory_item_id),
    CONSTRAINT ck_shipment_item_quantity CHECK ( quantity > 0 )
);
CREATE INDEX idx_shipment_item_inventory_item ON shipment_item (inventory_item_id);
